### ISSUE TITLE
Off-by-one in special case of array index selection

### ISSUE THREAD

**Issue by tomek-o** [suikabreaker/Janssonpath2#2]
Hello,
I think there is one element missing in array range selection if "end" in selection is equal or larger than array size.
With example JSON:
```
{
   "address" : {
      "city" : "Nara",
      "postalCode" : "630-0192",
      "streetAddress" : "naist street"
   },
   "age" : 26,
   "firstName" : "John",
   "lastName" : "doe",
   "phoneNumbers" : [
      {
         "number" : "0123-4567-8888",
         "type" : "iPhone"
      },
      {
         "number" : "0123-4567-8999",
         "type" : "home"
      },
      {
         "number" : "0123-9971-8910",
         "type" : "work"
      }
   ]
}
```
path $.phoneNumbers[1:3] returns only one element, but should return 2 elements (second and third one, taking http://jsonpath.com as reference).

Function json_array_index_translate() limits "end" index to array_size - 1 here
https://github.com/suikabreaker/Janssonpath2/blob/05b6ede9ebb61b84f3e4b4f1ad706ab2a914866e/src/evaluate.c#L299
but it should allow array_size value as there is "<end" condition few lines below (as end of range is not included in selection).

My workaround was adding/using second version of json_array_index_translate() function that limits to array_size, not array_size - 1:

```
static long long json_array_index_translate(json_int_t index, size_t array_size){
	if (index < 0) index = array_size + index; // for -n
	{
		long long ret = (index < 0) ? 0 : index;
		if ((size_t)ret >= array_size) ret = array_size - 1;
		return ret;
	}
}

static long long json_array_end_index_translate(json_int_t index, size_t array_size){
	if (index < 0) index = array_size + index; // for -n
	{
		long long ret = (index < 0) ? 0 : index;
		if ((size_t)ret > array_size) ret = array_size;
		return ret;
	}
}
```

Sorry this is not a PR, I'm working with slightly modified sources (Borland, C89) at the moment.

**Comment by suikabreaker** [comment]
An easier fix is to use an inclusive range. Fixed.

**Comment by suikabreaker** [comment]
Also, you can propose C89 compliance in a distinct issue.
