### ISSUE TITLE
Constants with more than 32 bits defined with "u" suffix

### ISSUE THREAD

**Issue by tomek-o** [suikabreaker/Janssonpath2#4]
This is a minor issue, but there is about a dozen constants larger than 32-bit range defined with "u" suffix instead of "ull" (if they were meant to exceed 32-bit range) like this:
https://github.com/suikabreaker/Janssonpath2/blob/05b6ede9ebb61b84f3e4b4f1ad706ab2a914866e/src/compile.c#L501
They are easy to find - searching for "0000" string.

**Comment by suikabreaker** [comment]
You are correct. Fixed.
